Article.create(title: "Improvement of motor development and postural control following intervention in children with SNHL and vestibular impairment", author: "Rine", evidence_level: 1, study_design: "randomized controlled trial", sub_section: "V/M")
Article.create(title: "Effect of vestibular dysfunction on the development on gross motor function in children with profound hearing loss", author: "Inoue",  evidence_level: 3, study_design: "retro-spective study", sub_section: "V/M")
Article.create(title: "The Importance of Saccular FUnction to Motor Development in Children with Hearing Impairments", author: "Shall", evidence_level: 2, study_design: "two group non-randomized", sub_section: "V/M")
Article.create(title: "Balance performance in children with unilateral and bilateral severe-to-profound-grade hearing impairment", author: "Wong", evidence_level: 2,study_design: "cross-sectional study", sub_section: "V/M")
Article.create(title: "The influence of a vestibular dysfunction on the motor development of hearing impaired children", author: "Kegel", evidence_level: 2, study_design: "cross-sectional", sub_section: "V/M")
Article.create(title: "Motor skills deficits in children with partial hearing", author: "Livingstone", evidence_level: 2,study_design: "non-randomized study", sub_section: "V/M")
Article.create(title: "A comparison of motor abilities and precieved self-effecacy between children with hearing Impairments and normal hearing children", author: "Engel-Yeger", evidence_level: 2, study_design: "two groups non-randomized", sub_section: "V/M")
Article.create(title: "Evidence of vestibular and Balance dysfunction in children with profound SNHL using cocular implants", author: "Cushing", evidence_level: 2, study_design: "prospective cross-sectional study with repeated measures", sub_section: "V/M")
Article.create(title: "Balance sensory organization in children with profound hearing loss and cocular implants", author: "Suarez", evidence_level: 2, study_design: "cross-sectional study", sub_section: "V/M")
Article.create(title: "Affect of Motor control program in imporving gros motor fucntion and postural control in children with SNHL-a pilot study", author: "Shah", evidence_level: 3, study_design: "pre-post test trial", sub_section: "V/M")
Article.create(title: "Growing evidence for balance and vestibular problems in children", author: "Rine", evidence_level: 5, study_design: "Lit Review", sub_section: "V/M")
Article.create(title: "The potential use of virtual reality in vestibular rehabilitation: preliminary findings with the BNAV", author: "Whitney", evidence_level: 2, study_design: "case control", sub_section: "V/M")
Article.create(title: "Vestibular end-organ dysfunction in children with SNHL and cocular implants an expanded cohort and etiologic assessment", author: "Cushing", evidence_level: 2, study_design: "Prospective and cross-sectional with repeated measures", sub_section: "V/M")
Article.create(title: "Achieving developmental synchrony in young children with hearing loss", author: "Mellon", evidence_level: 5, study_design: "expert opinion", sub_section: "V/M EF")
Article.create(title: "Comparison of health related quality of life of primary school deaf children with and without motor impairment", author: "Rajendran", evidence_level: 2, study_design: "Prospective cross-sectional study", sub_section: "V/M")
Article.create(title: "Affect of exercise intervention on vestibular related impairments in hearing impaired children", author: "Rajendran", evidence_level: 1, study_design: "Systematic Review", sub_section: "V/M")
Article.create(title: "A preliminary randomized controlled study on the effectiveness of vestibular specific neuro-muscular training in children with hearing impairment", author: "Rajendran", evidence_level: 1, study_design: "RCT", sub_section: "V/M")
Article.create(title: "Motor Development of deaf children with and without cocular implants", author: "Gheysen", evidence_level: 2, study_design: "Two groups non-randomized", sub_section: "V/M")
Article.create(title: "Balance and Motorskills in young children with sensory neuro-impairment", author: "Rine", evidence_level: 2 , study_design: "Two groups non-randomized", sub_section: "V/M")
Article.create(title: "Age related balance changes in hearing impaired children", author: "Siegel", evidence_level: 2, study_design: "Cohort study", sub_section: "V/M")
Article.create(title: "Cocular outcomes in children with motor developmental delay", author: "Amirsalari", evidence_level: 2, study_design: "Cohort study", sub_section: "V/M")
Article.create(title: "Pediatric vestibular evaluation: two children with SNHL", author: "Valente", evidence_level: 5, study_design: "Case Reports", sub_section: "V/M")
Article.create(title: "Evidence that vestibular hpyo-function effects reading acuity in children", author: "Braswell", evidence_level: 2, study_design: "Cohort study", sub_section: "V/M EF")
Article.create(title: "Attention demand and postural control in children with hearing deficit", author: "Derlich", evidence_level: 2, study_design: "Two groups non-randomized", sub_section: "V/M EF")
Article.create(title: "An overview of motor skill performance and balance in hearing impaired children", author: "Rajendran", evidence_level: 1, study_design: "Systematic Review", sub_section: "V/M")
Article.create(title: "Value of vestibular testing in young children with SNHL", author: "Angeli", evidence_level: 5, study_design: "Expert Opinion", sub_section: "V/M")
Article.create(title: "Balance and motor deficits and the role of Occupational Therapy in children who are deaf and hard of hearing: a critical appraisal of the topic", author: "Gronski", evidence_level: 1, study_design: "Systematic Review", sub_section: "V/M")

Article.create(title: "Executive functioning and the impact of a hearing loss: performance based measures and Behavior Rating Inventory of Executive Function (BRIEF)", author: "Oberg", evidence_level: 3, study_design: "One group non-randomized", sub_section: "EF")
Article.create(title: "Language ability and verbal and non-verbal executive functioning in deaf students communicating in spoken english", author: "Remine", evidence_level: 3, study_design: "One group non-randomized", sub_section: "EF")
Article.create(title: "Executive function and language in deaf children", author: "Figueras", evidence_level: 4, study_design: "Descriptive Study", sub_section: "EF")
Article.create(title: "Executive function in everyday life: Implications for young cocular implant users", author: "Beer", evidence_level: 4, study_design: "Descriptive Study", sub_section: "EF")
Article.create(title: "Executive functions and Behavioral problems in deaf and hard of hearing students at general and special schools", author: "Hintermayir", evidence_level: 4, study_design: "Descriptive Study", sub_section: "EF")
Article.create(title: "Exergaming immediately enhances children's executive function", author: "Best", evidence_level: 3, study_design: "Pre- and post-test", sub_section: "EF")
Article.create(title: "Inter-regional brain interactions in children with unilateral hearing loss", author: "Tibbetts", evidence_level: 3, study_design: "Perspective observational study", sub_section: "EF")
Article.create(title: "Predicting behavior in deaf and hearing children: the influences of language, attention, and parent-child communication", author: "Barker", evidence_level: 2, study_design: "Cross-sectional", sub_section: "EF")
Article.create(title: "Facial expression recognition: Can preschoolers with cocular implants and hearing aids catch it?", author: "Wang", evidence_level: 2, study_design: "Two groups non-randomized", sub_section: "EF")
Article.create(title: "Infants vs. older Children fitted with cocular implants: Performance over ten years", author: "Colletti", evidence_level: 2, study_design: "Prospective Cohort Study", sub_section: "EF")
Article.create(title: "Multiple effects of childhoold deafness on cortical activity in children recieving bilateral cocular implants simultaneously", author: "Gordon", evidence_level: 3, study_design: "One group non-randomized", sub_section: "EF")
Article.create(title: "Children with cocular implants and developmental disabilites: A language skills study with developmentally matched hearing peers", author: "Meinzen-Derr", evidence_level: 2, study_design: "Cross-sectional", sub_section: "EF")

Article.create(title: "Reading vocabulary in children with and without hearing loss: the roles of task and word type", author: "Coppens", evidence_level: 2, study_design: "Longitudal Study", sub_section: "EF")

Article.create(title: "The relationship between non-verbal cognitave functions and hearing loss", author: "Zekveld", evidence_level: 3, study_design: "One group non-randomized", sub_section: "EF")
Article.create(title: "Binaural temporal fine structure sensitivity, cognitave function, and spatial speech recognition in hearing impaired listeners", author: "Neher", evidence_level: 3, study_design: "One group non-randomized", sub_section: "EF")
Article.create(title: "Longitudal Functional Performance among children with cocular implants and disabilites: a prospective sutdy using the Pediatric Evaluation of Disability and Inventory", author: "Wiley", evidence_level: 3, study_design: "Prospective Study", sub_section: "EF")
Article.create(title: "Working Memory and Novel Word Learning in children with hearing impairment and children with specific language impairment", author: "Hansson", evidence_level: 2, study_design: "Cross-sectional", sub_section: "EF")

Article.create(title: "comparison of outcomes in children with hearing aids and cocular implants", author: "Fitzpatrick", evidence_level: 2, study_design: "retro-spective cohort", sub_section: "EF")
Article.create(title: "reading comprehension of deaf children with cocular implants", author: "Vermeulen", evidence_level: 2, study_design: "Cross-sectional", sub_section: "EF")
Article.create(title: "Auditory Sequential Organization among children with and without a hearing loss", author: "Jutras", evidence_level: 2, study_design: "Cross-sectional", sub_section: "EF")
Article.create(title: "Working memory in children with cocular implants: Problems are in storage, not processing", author: "Nittrouer", evidence_level: 2, study_design: "Cross-sectional", sub_section: "EF")
Article.create(title: "Pilot Study of cognition in children with unilateral hearing loss", author: "Ead", evidence_level: 2, study_design: "Cross-sectional", sub_section: "EF")
